version: '3.8'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker
    volumes:
      - .:/app
    ports:
      - 8008:8000
    # depends_on:
      # - db  # Indic
  # aiogram:
  #   build: .
  #   command: python -u bot.py  # Update the path to bot.py
  #   volumes:
  #     - .:/app  # Map the telegram folder to the container's /telegram directory
  #   depends_on:
  #     - db
#   db:
#     image: postgres:13.3
#     container_name: postgres_db
#     restart: always
#     environment:
#       POSTGRES_DB: postgres        # Replace 'testbot' with your desired database name
#       POSTGRES_USER: postgres    # Replace 'postgres' with your desired username
#       POSTGRES_PASSWORD: 77girado  # Replace '77girado' with your desired password
#     ports:
#       - "5432:5432"   # Expose port 5432 on the host to connect to PostgreSQL
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:


  


  